### ISSUE TITLE
Plans for LaTeX?

### ISSUE THREAD

**Issue by francescoalemanno** [mmMike/marko-editor#2]
Hallo! 
are there any plans to support LaTeX formulas within Marko?

**Comment by mmMike** [comment]
Hi, images are planned, and formulas would probably be images. However, with Marko I'm currently only scratching my own itch, and formulas are currently not that important for me. It's more the OneNote direction,  knowledge maps.

**Comment by RyanGreenup** [comment]
For what it's worth I think implementing KaTeX or Mathjax would be a really nice addition (Maybe also full-text search with something like [tantivy](https://github.com/tantivy-search/tantivy)).

**Comment by mmMike** [comment]
>  Maybe also full-text search ...

What are you missing with the current search functionality?
